export const STORYID_LOADING = 'STORYID_LOADING';
export const ADD_STORY = 'ADD_STORY';
export const STORY_FAILURE = 'STORY_FAILURE';
export const STORYID_FAILURE = 'STORYID_FAILURE';
export const STORY_LOADING = 'STORY_LOADING';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILURE = 'COMMENTS_FAILURE';
export const STORIES_FAILURE = 'STORIES_FAILURE';
